// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6KP_hH02ghFQqJe1K2KYT9VawDxLyz24',
    appId: '1:854978837877:web:65c424ff804020e3f1a73c',
    messagingSenderId: '854978837877',
    projectId: 'signagestor',
    authDomain: 'signagestor.firebaseapp.com',
    storageBucket: 'signagestor.appspot.com',
    measurementId: 'G-FZTXEFPKHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5vfvUZ_XRBxXQ3x__hKOM_zTo4xcLy6o',
    appId: '1:854978837877:android:ee1619f8fa29ec1ff1a73c',
    messagingSenderId: '854978837877',
    projectId: 'signagestor',
    storageBucket: 'signagestor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlA0XclS2Jd5lVInkH3K1yOs5lHDl5HbE',
    appId: '1:854978837877:ios:1d1f96d50fa5d934f1a73c',
    messagingSenderId: '854978837877',
    projectId: 'signagestor',
    storageBucket: 'signagestor.appspot.com',
    iosBundleId: 'com.example.signagestor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlA0XclS2Jd5lVInkH3K1yOs5lHDl5HbE',
    appId: '1:854978837877:ios:1d1f96d50fa5d934f1a73c',
    messagingSenderId: '854978837877',
    projectId: 'signagestor',
    storageBucket: 'signagestor.appspot.com',
    iosBundleId: 'com.example.signagestor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6KP_hH02ghFQqJe1K2KYT9VawDxLyz24',
    appId: '1:854978837877:web:4efe0ed9101ba1d8f1a73c',
    messagingSenderId: '854978837877',
    projectId: 'signagestor',
    authDomain: 'signagestor.firebaseapp.com',
    storageBucket: 'signagestor.appspot.com',
    measurementId: 'G-V5QM4RTGKY',
  );
}
